spring:
  application:
    name: 18comic-assistant
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  proxy:
    mode: manual
    host: 127.0.0.1
    port: 12334
  upload:
    strategy: local
    url: /vertx-comic
  comic:
    host: https://18comic-rajang.cc
    username: idolysfsdf
    password: zxcvbnm159456
  ai:
    openai:
      api-key: sk-be0bee62e5364e0387c6511ceab4f3e2
      base-url: https://api.deepseek.com
      chat.options.model: deepseek-chat