spring:
  application:
    name: 18comic-assistant
  main:
    banner-mode: off
  output:
    ansi:
      enabled: always
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates/
    cache: false
  h2:
    console.enabled: true # /h2-console
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    # show-sql: true
    # properties:
    #   hibernate.format_sql: true
  datasource:
    url: jdbc:h2:file:./data;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  comic:
    username: idolysfsdf
    password: zxcvbnm159456
    urls: https://18comic.org
    user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36 Edg/134.0.0.0
    proxy:
      host: 127.0.0.1
      port: 12334
  ai:
    deepseek:
      api-key: sk-c63749802f29483cba33e2e596bd7f87
      chat:
        options:
          responseFormat.type: json_object