spring:
  application:
    name: 18comic-assistant
  main:
    banner-mode: off
  output:
    ansi:
      enabled: always
  h2:
    console.enabled: true # /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    # show-sql: true
    # properties:
    #   hibernate.format_sql: true
  datasource:
    url: jdbc:h2:file:./data;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  comic:
    urls: https://18comic.org, "https://jmcomic-zzz.one", http://18comic-daima.cc
    user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36 Edg/134.0.0.0
    proxy:
      host: 127.0.0.1
      port: 12334
  ai:
    openai:
      api-key: sk-be0bee62e5364e0387c6511ceab4f3e2
      base-url: https://api.deepseek.com
      chat.options.model: deepseek-chat